# Generated by Django 2.1.7 on 2019-03-07 07:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_auto_20190307_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_messages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
