# Generated by Django 2.1.7 on 2019-03-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0003_my_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_messages',
            name='id',
            field=models.UUIDField(default='<functio', editable=False, primary_key=True, serialize=False),
        ),
    ]
