# Generated by Django 2.1.7 on 2019-03-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0005_auto_20190307_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('title',)},
        ),
    ]
